var _locate_message_cn = {
	"scan_page" : {
	    "SCAN_MSG_1" : "依据《旅客治安管理条例》的要求，",
	    "SCAN_MSG_2" : "住宿宾客“必须实名登记，一人一证”",
	    "SCAN_MSG_3" : "秒后自动退出",
	    "SCAN_MSG_4" : "您的身份信息已添加",
	    "SCAN_MSG_5" : "请将您的身份证放在扫描区进行扫描",
	    "SCAN_MSG_6" : "您的证件扫描成功，正在请求订单，请稍后...",
	    "SCAN_MSG_7" : "请刷身份证",
	    "SCAN_MSG_8" : "未查到您的订单，请选择其他方式查询",
	    "scan_def_tip" : "请将身份证放到扫描区",
	    "scan_fail_tip" : "证件读取错误，请重试!",
	    "scan_getorder_tip" : "请求订单中...",
	    "SCAN_MSG_9" : "开始扫描身份证...",
	    "SCAN_MSG_10" : "扫描身份证成功",
	    "SCAN_MSG_11" : "开始人脸识别...",
	    "SCAN_MSG_12" : "人脸识别成功",
	    "SCAN_MSG_13" : "人脸识别失败",
	    "SCAN_MSG_14" : "人脸识别失败，无数据返回",
	    "SCAN_MSG_15" : "打开闪光灯",
	    "SCAN_MSG_16" : "关闭闪光灯",
	    "SCAN_MSG_17" : "读取身份证数据为空",
	    "SCAN_MSG_18" : "人脸识别无法使用，请联系厂家处理。"
	},
	"order_page" : {
	    "ORDER_MSG_1" : "<CNANE>先生<DTIME>，欢迎使用入住<HOTEL>，请您有<ONUM>个需要办理的订单",
	    "ORDER_MSG_2" : "<CNANE>女士<DTIME>，欢迎使用入住<HOTEL>，请您有<ONUM>个需要办理的订单",
	    "ORDER_MSG_3" : "<CNANE>先生，您已支付成功，请确认入住",
	    "ORDER_MSG_4" : "<CNANE>女士，您已支付成功，请确认入住",
	    "ORDER_MSG_5" : "（点x取消入住人或者更改入住人）",
	    "ORDER_MSG_6" : "您的订单总价为：",
	    "ORDER_MSG_7" : "，请选择以下支付方式进行支付",
	    "ORDER_MSG_8" : "现金",
	    "ORDER_MSG_9" : "刷卡",
	    "ORDER_MSG_10" : "微信",
	    "ORDER_MSG_11" : "支付宝",
	    "ORDER_MSG_12" : "已通知工作人员前来收款",
	    "ORDER_MSG_13" : "请稍后......",
	    "ORDER_MSG_14" : "请使用侧面pos机",
	    "ORDER_MSG_15" : "刷银联卡支付",
	    "ORDER_MSG_16" : "请使用微信",
	    "ORDER_MSG_17" : "扫描下面的二维码支付",
	    "ORDER_MSG_18" : "请使用支付宝",
	    "ORDER_MSG_19" : "元",
	    "ORDER_MSG_20" : "入住时间：",
	    "ORDER_MSG_21" : "退房时间：",
	    "ORDER_MSG_22" : "入住人",
	    "ORDER_MSG_23" : "房间号：",
	    "ORDER_MSG_24" : "总房价",
	    "ORDER_MSG_25" : "没有支付信息",
	    "ORDER_MSG_26" : "退房成功",
	    "ORDER_MSG_27" : "已退房：",
	    "ORDER_MSG_28" : "您的房间号码：",
	    "ORDER_MSG_29" : "入住完成。祝您入住愉快",
	    "ORDER_MSG_30" : "温馨提示您：",
	    "ORDER_MSG_31" : "正通知前台员工授权确认支付",
	    "ORDER_MSG_32":"等待POS刷银行卡支付......",
	    "ORDER_MSG_33":"等待支付......",
	    "ORDER_MSG_34" : "<CNANE>先生，您好！欢迎使用入住<HOTEL>，请选择您需要预定的房型",
	    "ORDER_MSG_35" : "<CNANE>女士，您好！欢迎使用入住<HOTEL>，请选择您需要预定的房型",
	    "ORDER_MSG_36" : "<CNANE>先生，请选择您需要楼层和房间",
	    "ORDER_MSG_37" : "<CNANE>女士，请选择您需要楼层和房间",
	    "ORDER_MSG_38" : '如果您有同伴请一定要点击“添加”把您的同伴增加进来',
	    "ORDER_MSG_39" : "<CNANE>先生，您的订单未支付，请确认支付",
	    "ORDER_MSG_40" : "<CNANE>女士，您的订单未支付，请确认支付",
	    "ORDER_MSG_41" : "是否确认现金支付?",
	    "ORDER_MSG_42" : "是否确认POS支付?",
	    "ORDER_MSG_43" : "<CNANE>先生，",
	    "ORDER_MSG_44" : "<CNANE>女士，",
	    "ORDER_MSG_45" : "入住资料审核失败，请联系前台！",
	    "ORDER_MSG_46" : "入住审核已成功，正在制作房卡，请稍等......",
	    "ORDER_MSG_47" : "您的房卡已制作成功，请取走您的房卡和打印单",
	    "ORDER_MSG_48" : "如果您想体验手机开门，请扫描二维码关注微信公众号",
	    "ORDER_MSG_49" : "如果您想体验智能客控，请扫描二维码关注微信公众号",
	    "ORDER_MSG_50" : "期待您再次光临<HOTEL>",
	    "ORDER_MSG_51" : "向右滑动屏幕查看更多订单",
	    "ORDER_MSG_52" : "发卡失败",
	    "ORDER_MSG_53" : "为给您提供更好的服务，请留下您的手机号",
	    "ORDER_MSG_54" : "获取订单信息失败，请联系前台！",
	    "ORDER_MSG_55" : "入住人",
		"ORDER_MSG_56" : "换房",
		"ORDER_MSG_57" : "没有查到订单，请确认输入",
		"ORDER_MSG_58" : "请输入订单预订号查询订单",
	    "ORDER_MSG_59" : "<CNANE>先生，您可以领取您的房卡",
	    "ORDER_MSG_60" : "<CNANE>女士，您可以领取您的房卡",
	    "ORDER_MSG_61" : "您是要退房吗？",
	    "ORDER_MSG_62" : "根据您的证件未查单您的订单",
	    "ORDER_MSG_63" : "您的订单续住成功，欢迎入住",
	    "ORDER_MSG_64" : "支付请求中...",
	    "ORDER_MSG_65" : "支付请求超时，请重试",
	    "SCAN_MSG_3" : "秒后自动退出",
	    "scan_def_tip" : "请将身份证放到扫描区",
	    "scan_fail_tip" : "证件读取错误，请重试!",
	    "scan_getorder_tip" : "请求订单中...",
	    "scan_success_tip" : "身份证扫描成功，正在请求订单中..."
	},
	"footer_msg" : {
	    "FT_MSG_0001" : "刷身份证",
	    "FT_MSG_0002" : "确认订单",
	    "FT_MSG_0003" : "确认支付",
	    "FT_MSG_0004" : "领取房卡",
	    "FT_MSG_0005" : "请求订单中...",
	    "FT_MSG_0006" : "身份证扫描成功，正在请求订单中...",
	    "FT_MSG_0007" : "插入房卡",
	    "FT_MSG_0008" : "确认退房",
	    "FT_MSG_0009" : "确认入住",
	    "FT_MSG_0010" : "查询订单"
	},
	"btn_name" : {
		"retry":"重试",
		"ok":"确定",
		"no":"取消",
		"BTN_MSG_001":"安全退出",
		"BTN_MSG_002":"再领一张",
		"BTN_MSG_003":"预约发票",
		"BTN_MSG_004":"下一步",
		"BTN_MSG_005":"入住",
		"BTN_MSG_006":"退房",
		"BTN_MSG_007":"续住",
		"BTN_MSG_008":"其他方式查询订单",
		"BTN_MSG_009" : "办理入住",
		"BTN_MSG_010" : "领取房卡",
		"BTN_MSG_011" : "我要支付",
		"BTN_MSG_012" : "我要退房",
		"BTN_MSG_013" : "继续办理",
		"BTN_MSG_014" : "我要预订",
		"BTN_MSG_015" : "确认",
		"BTN_MSG_016" : "处理中...",
		"BTN_MSG_017" : "完成"
	},
	"nav_title" : {
		"TITLE_ROOM_TYPE":"房型",
		"TITLE_RES_DAYS":"天数",
		"TITLE_ROOMNO":"房号",
		"TITLE_ROOM_PRICE":"房价"
	},
	"common_tip" : {
		"HELLO_01":"早上好",
		"HELLO_02":"上午好",
		"HELLO_03":"中午好",
		"HELLO_04":"下午好",
		"HELLO_05":"傍晚好",
		"HELLO_06":"晚上好",
		"HELLO_07":"夜里好",
		"HELLO_08":"凌晨好",
		"SEND_CARD_TIPS_1":"系统已向前台工作人员发送制卡请求",
		"SEND_CARD_TIPS_2":"前台员工授权后，系统自行发放房卡",
		"SEND_CARD_TIPS_3":"请稍后...",
		"AUTH_PAY_TIPS_1":"系统已向前台工作人员支付授权请求",
		"AUTH_CARD_AUTH_READ_FAIL":"授权卡读取失败，请重试！",
		"ASSIGN_ROOM_FAIL":"排房失败，请重试！",
		"AUTH_CARD_AUTH_SUCCESS":"授权成功！",
		"PAY_SUCCESS":"支付成功！",
		"NO_ROOM_SELECT":"请选择入住的房间",
		"CHECK_PERSON_INFO":"请前台员工认证客人的身份信息。",
		"AUTH_CARD_AUTH_FAIL":"授权失败，请重试！",
		"CREATE_ORDER_FAIL":"下单失败，请重试！",
		"AUTH_READ_CARD_FAIL":"读取房卡失败，请重试！",
		"SEND_CARD_FAIL":"发卡失败，请重试！",
		"TAKE_CARD_PLEASE":"请取卡",
		"CARD_IN_READ_ERROR":"卡机塞卡，请联系前台处理！",
		"CARD_READ_ERROR":"读取房卡错误，请联系前台处理！",
		"SENDING_CARD":"发卡中...",
		"READING_CARD":"正在读卡...",
		"READ_CARD_SUCCESS_TO_CHECKOUT":"读卡成功,正在退房...",
		"READY_SEND_CARD":"准备发卡",
		"INSERT_CARD_PLEASE":"请插入房卡",
		"SUCCESS_SEND_CARD":"发卡成功，请取卡。",
		"NO_SELECT_ROOM":"没有选择房间，请重试！",
	    "net_time_out" : "网络超时，请重试",
	    "SAVE_SUCCESS" : "保存成功",
	    "ws_connect_error" : "设备连接失败，请重试",
	    "waite_for_back_home" : "等待时间过长，继续操作？",
		"WS_DEV_USING":"设备使用中，请重试！",
		"WS_DEV_UNKNOW":"设备连接错误，请重试！",
		"NO_USEABLE_ROOM":"暂无可用房，请联系前台处理！",
		"WS_CONNECT_SUCCESD":"设备连接成功！",
		"WS_CONNECT_FAIL":"设备连接失败！",
		"WS_CONNECT_CLOSE":"设备断开连接！",
		"COMMON_MSG_001":"唯一房间",
		"COMMON_MSG_002":"没有房间",
		"COMMON_MSG_003":"发卡槽无卡，请放置房卡",
		"COMMON_MSG_004":"已取卡",
		"COMMON_MSG_005":"如果想体验手机开门，",
		"COMMON_MSG_006":"请扫描二维码哦",
		"COMMON_MSG_007":"请扫描微信小程序哦",
		"COMMON_MSG_008":"获取设备信息失败，请重试",
		"COMMON_MSG_009":"设置设备信息成功",
		"COMMON_MSG_010":"设置设备信息失败",
		"COMMON_MSG_011":"请您填写正确的手机号",
		"COMMON_MSG_012":"月",
		"COMMON_MSG_013":"日",
		"COMMON_MSG_014":"周一",
		"COMMON_MSG_015":"周二",
		"COMMON_MSG_016":"周三",
		"COMMON_MSG_017":"周四",
		"COMMON_MSG_018":"周五",
		"COMMON_MSG_019":"周六",
		"COMMON_MSG_020":"周日",
		"COMMON_MSG_021":"欢迎光临",
		"COMMON_MSG_022":"copyright@devok 20190201",
		"COMMON_MSG_023":"没有房间",
		"COMMON_MSG_024":"换一间房",
		"COMMON_MSG_025":"姓名：",
		"COMMON_MSG_026":"邮箱：",
		"COMMON_MSG_027":"账单号：",
		"COMMON_MSG_028":"房间号：",
		"COMMON_MSG_029":"天数：",
		"COMMON_MSG_030":"抵店日期：",
		"COMMON_MSG_031":"离店日期：",
		"COMMON_MSG_032":"日期",
		"COMMON_MSG_033":"说明",
		"COMMON_MSG_034":"付款",
		"COMMON_MSG_035":"操作时间过长，是否继续？",
		"COMMON_MSG_036":"总计",
		"COMMON_MSG_037":"消费",
		"COMMON_MSG_038":"余额",
		"COMMON_MSG_039":'请前台工作人员核实支付信息。<br>支付金额Y<span style="font-size:1.3rem;color:red;">【[TOTALAMOUNT]】</span>',
		"COMMON_MSG_040":'请您到前台办理多房间的订单，谢谢！',
		"COMMON_MSG_041":'请输入正确的订单号！',
		"COMMON_MSG_042":'或',
		"COMMON_MSG_043" :"离店日期",
		"COMMON_MSG_044":"请添加入住客人信息",
		"COMMON_MSG_045":"请扫描您的证件添加入住信息，感谢您的光临！",
		"COMMON_MSG_046":"卡片无法识别，请重新确认",
		"COMMON_MSG_047":"读取卡片失败，请联系前台处理",
		"COMMON_MSG_048":"注销卡成功",
		"COMMON_MSG_049":"注销卡失败",
		"COMMON_MSG_050":"没有可用房",
		"COMMON_MSG_051":"没有取到订单信息",
		"COMMON_MSG_052":"发卡返回数据为空",
		"COMMON_MSG_053":"读取卡信息数据为空"
	}
}
var _locate_message_en = {
	"scan_page" : {
	    "SCAN_MSG_1" : "依据《旅客治安管理条例》的要求，",
	    "SCAN_MSG_2" : "住宿宾客“必须实名登记，一人一证”",
	    "SCAN_MSG_3" : "秒后自动退出",
	    "SCAN_MSG_4" : "您的身份信息已添加",
	    "SCAN_MSG_5" : "请将您的身份证放在扫描区进行扫描",
	    "SCAN_MSG_6" : "您的证件扫描成功，正在请求订单，请稍后...",
	    "SCAN_MSG_7" : "请刷身份证",
	    "SCAN_MSG_8" : "未查到您的订单，请选择其他方式查询",
	    "scan_def_tip" : "请将身份证放到扫描区",
	    "scan_fail_tip" : "证件读取错误，请重试!",
	    "scan_getorder_tip" : "请求订单中...",
	    "SCAN_MSG_9" : "开始扫描身份证...",
	    "SCAN_MSG_10" : "扫描身份证成功",
	    "SCAN_MSG_11" : "开始人脸识别...",
	    "SCAN_MSG_12" : "人脸识别成功",
	    "SCAN_MSG_13" : "人脸识别失败",
	    "SCAN_MSG_14" : "人脸识别失败，无数据返回",
	    "SCAN_MSG_15" : "打开闪光灯",
	    "SCAN_MSG_16" : "关闭闪光灯",
	    "SCAN_MSG_17" : "读取身份证数据为空",
	    "SCAN_MSG_18" : "人脸识别无法使用，请联系厂家处理。"
	},
	"order_page" : {
	    "ORDER_MSG_1" : "<CNANE>先生<DTIME>，欢迎使用入住<HOTEL>，请您有<ONUM>个需要办理的订单",
	    "ORDER_MSG_2" : "<CNANE>女士<DTIME>，欢迎使用入住<HOTEL>，请您有<ONUM>个需要办理的订单",
	    "ORDER_MSG_3" : "<CNANE>先生，您已支付成功，请确认入住",
	    "ORDER_MSG_4" : "<CNANE>女士，您已支付成功，请确认入住",
	    "ORDER_MSG_5" : "（点x取消入住人或者更改入住人）",
	    "ORDER_MSG_6" : "您的订单总价为：",
	    "ORDER_MSG_7" : "，请选择以下支付方式进行支付",
	    "ORDER_MSG_8" : "现金",
	    "ORDER_MSG_9" : "刷卡",
	    "ORDER_MSG_10" : "微信",
	    "ORDER_MSG_11" : "支付宝",
	    "ORDER_MSG_12" : "已通知工作人员前来收款",
	    "ORDER_MSG_13" : "请稍后......",
	    "ORDER_MSG_14" : "请使用侧面pos机",
	    "ORDER_MSG_15" : "刷银联卡支付",
	    "ORDER_MSG_16" : "请使用微信",
	    "ORDER_MSG_17" : "扫描下面的二维码支付",
	    "ORDER_MSG_18" : "请使用支付宝",
	    "ORDER_MSG_19" : "元",
	    "ORDER_MSG_20" : "入住时间：",
	    "ORDER_MSG_21" : "退房时间：",
	    "ORDER_MSG_22" : "入住人：",
	    "ORDER_MSG_23" : "房间号：",
	    "ORDER_MSG_24" : "总房价：",
	    "ORDER_MSG_25" : "没有支付信息",
	    "ORDER_MSG_26" : "退房成功",
	    "ORDER_MSG_27" : "已退房：",
	    "ORDER_MSG_28" : "您的房间号码：",
	    "ORDER_MSG_29" : "入住完成。祝您入住愉快",
	    "ORDER_MSG_30" : "温馨提示您：",
	    "ORDER_MSG_31" : "正通知前台员工授权确认支付",
	    "ORDER_MSG_32":"等待POS刷银行卡支付......",
	    "ORDER_MSG_33":"等待支付......",
	    "ORDER_MSG_34" : "<CNANE>先生，您好！欢迎使用入住<HOTEL>，请选择您需要预定的房型",
	    "ORDER_MSG_35" : "<CNANE>女士，您好！欢迎使用入住<HOTEL>，请选择您需要预定的房型",
	    "ORDER_MSG_36" : "<CNANE>先生，请选择您需要楼层和房间",
	    "ORDER_MSG_37" : "<CNANE>女士，请选择您需要楼层和房间",
	    "ORDER_MSG_38" : '如果您有同伴请一定要点击“添加”把您的同伴增加进来',
	    "ORDER_MSG_39" : "<CNANE>先生，您的订单未支付，请确认支付",
	    "ORDER_MSG_40" : "<CNANE>女士，您的订单未支付，请确认支付",
	    "ORDER_MSG_41" : "是否确认现金支付?",
	    "ORDER_MSG_42" : "是否确认POS支付?",
	    "ORDER_MSG_43" : "<CNANE>先生，",
	    "ORDER_MSG_44" : "<CNANE>女士，",
	    "ORDER_MSG_45" : "入住资料审核失败，请联系前台！",
	    "ORDER_MSG_46" : "入住审核已成功，正在制作房卡，请稍等......",
	    "ORDER_MSG_47" : "您的房卡已制作成功，请取走您的房卡和打印单",
	    "ORDER_MSG_48" : "如果您想体验手机开门，请扫描二维码下载APP",
	    "ORDER_MSG_49" : "如果您想体验手机开门，请扫描二维码关注微信公众号",
	    "ORDER_MSG_50" : "期待您再次光临<HOTEL>",
	    "ORDER_MSG_51" : "向右滑动屏幕查看更多订单",
	    "ORDER_MSG_52" : "发卡失败",
	    "ORDER_MSG_53" : "请填写您的手机号",
	    "ORDER_MSG_54" : "获取订单信息失败，请联系前台！",
	    "SCAN_MSG_3" : "秒后自动退出",
	    "scan_def_tip" : "请将身份证放到扫描区",
	    "scan_fail_tip" : "证件读取错误，请重试!",
	    "scan_getorder_tip" : "请求订单中...",
	    "scan_success_tip" : "身份证扫描成功，正在请求订单中..."
	},
	"footer_msg" : {
	    "FT_MSG_0001" : "刷身份证",
	    "FT_MSG_0002" : "确认订单",
	    "FT_MSG_0003" : "确认支付",
	    "FT_MSG_0004" : "领取房卡",
	    "FT_MSG_0005" : "请求订单中...",
	    "FT_MSG_0006" : "身份证扫描成功，正在请求订单中...",
	    "FT_MSG_0007" : "插入房卡",
	    "FT_MSG_0008" : "确认退房",
	    "FT_MSG_0009" : "确认入住",
	    "FT_MSG_0010" : "查询订单"
	},
	"btn_name" : {
		"retry":"重试",
		"ok":"确定",
		"BTN_MSG_001":"安全退出",
		"BTN_MSG_002":"再领一张",
		"BTN_MSG_003":"预约发票",
		"BTN_MSG_004":"下一步",
		"BTN_MSG_005":"CheckIn",
		"BTN_MSG_006":"CheckOut",
		"BTN_MSG_007":"Extension"
	},
	"nav_title" : {
		"TITLE_ROOM_TYPE":"房型",
		"TITLE_RES_DAYS":"天数",
		"TITLE_ROOMNO":"房号",
		"TITLE_ROOM_PRICE":"房价"
	},
	"common_tip" : {
		"HELLO_01":"早上好",
		"HELLO_02":"上午好",
		"HELLO_03":"中午好",
		"HELLO_04":"下午好",
		"HELLO_05":"傍晚好",
		"HELLO_06":"晚上好",
		"HELLO_07":"夜里好",
		"HELLO_08":"凌晨好",
		"SEND_CARD_TIPS_1":"系统已向前台工作人员发送制卡请求",
		"SEND_CARD_TIPS_2":"前台员工授权后，系统自行发放房卡",
		"SEND_CARD_TIPS_3":"请稍后...",
		"AUTH_PAY_TIPS_1":"系统已向前台工作人员支付授权请求",
		"AUTH_CARD_AUTH_READ_FAIL":"授权卡读取失败，请重试！",
		"ASSIGN_ROOM_FAIL":"排房失败，请重试！",
		"AUTH_CARD_AUTH_SUCCESS":"授权成功！",
		"PAY_SUCCESS":"支付成功！",
		"NO_ROOM_SELECT":"请选择入住的房间",
		"CHECK_PERSON_INFO":"支付成功！请前台员工认证客人的身份信息。",
		"AUTH_CARD_AUTH_FAIL":"授权失败，请重试！",
		"CREATE_ORDER_FAIL":"下单失败，请重试！",
		"AUTH_READ_CARD_FAIL":"读取房卡失败，请重试！",
		"SEND_CARD_FAIL":"发卡失败，请重试！",
		"TAKE_CARD_PLEASE":"请取卡",
		"CARD_IN_READ_ERROR":"卡机塞卡，请联系前台处理！",
		"CARD_READ_ERROR":"读取房卡错误，请联系前台处理！",
		"SENDING_CARD":"发卡中...",
		"READING_CARD":"正在读卡...",
		"READ_CARD_SUCCESS_TO_CHECKOUT":"读卡成功,正在退房...",
		"READY_SEND_CARD":"准备发卡",
		"INSERT_CARD_PLEASE":"请插入房卡",
		"SUCCESS_SEND_CARD":"发卡成功，请取卡。",
		"NO_SELECT_ROOM":"没有选择房间，请重试！",
	    "net_time_out" : "网络超时，请重试",
	    "SAVE_SUCCESS" : "保存成功",
	    "ws_connect_error" : "设备连接失败，请重试",
	    "waite_for_back_home" : "等待时间过长，继续操作？",
		"WS_DEV_USING":"设备使用中，请重试！",
		"WS_DEV_UNKNOW":"设备连接错误，请重试！",
		"NO_USEABLE_ROOM":"暂无可用房，请联系前台处理！",
		"WS_CONNECT_SUCCESD":"设备连接成功！",
		"WS_CONNECT_FAIL":"设备连接失败！",
		"WS_CONNECT_CLOSE":"设备断开连接！",
		"COMMON_MSG_001":"唯一房间",
		"COMMON_MSG_002":"没有房间",
		"COMMON_MSG_003":"发卡槽无卡，请放置房卡",
		"COMMON_MSG_004":"已取卡",
		"COMMON_MSG_005":"如果想体验手机开门，",
		"COMMON_MSG_006":"请扫描二维码哦",
		"COMMON_MSG_007":"请扫描微信小程序哦",
		"COMMON_MSG_008":"获取设备信息失败",
		"COMMON_MSG_009":"设置设备信息成功",
		"COMMON_MSG_010":"设置设备信息失败",
		"COMMON_MSG_011":"请您填写正确的手机号",
		"COMMON_MSG_012":"-",
		"COMMON_MSG_013":"",
		"COMMON_MSG_014":"Mon.",
		"COMMON_MSG_015":"Tue.",
		"COMMON_MSG_016":"Wed.",
		"COMMON_MSG_017":"Thu",
		"COMMON_MSG_018":"Fri.",
		"COMMON_MSG_019":"Sta.",
		"COMMON_MSG_020":"Sun.",
		"COMMON_MSG_021":"欢迎光临",
		"COMMON_MSG_022":"copyright@devok 20190201",
		"COMMON_MSG_023":"没有房间",
		"COMMON_MSG_024":"换一间房",
		"COMMON_MSG_025":"姓名：",
		"COMMON_MSG_026":"邮箱：",
		"COMMON_MSG_027":"账单号：",
		"COMMON_MSG_028":"房间号：",
		"COMMON_MSG_029":"天数：",
		"COMMON_MSG_030":"抵店日期：",
		"COMMON_MSG_031":"离店日期：",
		"COMMON_MSG_032":"日期",
		"COMMON_MSG_033":"说明",
		"COMMON_MSG_034":"付款",
		"COMMON_MSG_035":"操作时间过长，是否继续？",
		"COMMON_MSG_036":"总计",
		"COMMON_MSG_037":"消费",
		"COMMON_MSG_038":"余额",
		"COMMON_MSG_039":'请前台工作人员核实支付信息。<br>支付金额Y<span style="font-size:1.3rem;color:red;">【[TOTALAMOUNT]】</span>',
		"COMMON_MSG_040":'请您到前台办理多房间的订单，谢谢！',
		"COMMON_MSG_041":'请输入正确的订单号！',
		"COMMON_MSG_042":'或',
		"COMMON_MSG_043" :"离店日期",
		"COMMON_MSG_044":"请添加入住客人信息",
		"COMMON_MSG_045":"请扫描您的证件添加入住信息，感谢您的光临！",
		"COMMON_MSG_046":"卡片无法识别，请重新确认",
		"COMMON_MSG_047":"读取卡片失败，请联系前台处理",
		"COMMON_MSG_048":"注销卡成功",
		"COMMON_MSG_049":"注销卡失败",
		"COMMON_MSG_050":"没有可用房",
		"COMMON_MSG_051":"没有取到订单信息",
		"COMMON_MSG_052":"发卡返回数据为空",
		"COMMON_MSG_053":"读取卡信息数据为空"
	}
}

var _locate_message = _locate_message_cn;